Space101/Controllers/FlightController.cs
using AutoMapper;
using Space101.DAL;
using Space101.Dtos;
using Space101.Enums;
using Space101.Helper_Models;
using Space101.Hub_Services;
using Space101.Models;
using Space101.Persistence;
using Space101.Repositories;
using Space101.ViewModels.FlightPathViewModels;
using Space101.ViewModels.FlightViewModels;
using Space101.ViewModels.StarshipViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Space101.Controllers
{
    [Authorize(Roles = AvailableRoles.Admin + "," + AvailableRoles.DatabaseManager)]
    public class FlightController : Controller
    {
        private ApplicationDbContext context;
        private FlightRepository flightRepository;
        private FlightSeatRepository flightSeatRepository;
        private FlightStatusRepository flightStatusRepository;
        private FlightPathRepository flightPathRepository;
        private StarshipRepository starshipRepository;
        private UnitOfWork unitOfWork;

        public FlightController()
        {
            context = new ApplicationDbContext();
            flightRepository = new FlightRepository(context);
            flightSeatRepository = new FlightSeatRepository(context);
            flightStatusRepository = new FlightStatusRepository(context);
            flightPathRepository = new FlightPathRepository(context);
            starshipRepository = new StarshipRepository(context);
            unitOfWork = new UnitOfWork(context);
        }
        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }

        // GET: Flight
        [AllowAnonymous]
        public ActionResult Index()
        {
            var flights = flightRepository.GetFlights();
            var flightStatuses = flightStatusRepository.GetFlightStatuses();

            var viewModel = new List<FlightViewModel>();

            flights.ForEach(f => viewModel.Add(FlightViewModel.CreateFromModel(f, flightStatuses)));

            return View(viewModel);
        }

        public ActionResult New()
        {
            var lightFlightPaths = InitializeFlightPaths();
            var lightStarships = InitializeStarships();

            var viewModel = new ContainerFlightFormViewModel(new FlightFormViewModel(), lightFlightPaths, lightStarships);

            return View("FlightForm", viewModel);
        }

        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var flight = flightRepository.GetSingleFlight(id ?? (int)InvalidPropertyValues.undefinedValue);

            if (flight == null)
                return HttpNotFound();

            var lightFlightPaths = InitializeFlightPaths();
            var lightStarships = InitializeStarships();

            var viewModel = new ContainerFlightFormViewModel(new FlightFormViewModel(flight), lightFlightPaths, lightStarships);

            return View("FlightForm", viewModel);
        }

        private List<LightFlightPathViewModel> InitializeFlightPaths()
        {
            var flightPaths = flightPathRepository.GetFlightPaths();

            var viewmodels = new List<LightFlightPathViewModel>();
            flightPaths.ForEach(fp => viewmodels.Add(new LightFlightPathViewModel(fp)));

            return viewmodels;
        }

        private List<LightStarshipViewModel> InitializeStarships()
        {
            var starships = starshipRepository.GetStarships();

            var viewmodels = new List<LightStarshipViewModel>();
            starships.ForEach(s => viewmodels.Add(new LightStarshipViewModel(s)));

            return viewmodels;
        }

        public ActionResult Save(FlightFormViewModel flightFormViewModel)
        {
            if (!ModelState.IsValid)
            {
                var lightFlightPaths = InitializeFlightPaths();
                var lightStarships = InitializeStarships();

                var viewModel = new ContainerFlightFormViewModel(flightFormViewModel, lightFlightPaths, lightStarships);
                return View("FlightForm", viewModel);
            }

            Flight flightToDB;

            if (flightFormViewModel.FlightId == 0)
            {
                var starship = starshipRepository.GetSingleStarship(flightFormViewModel.StarshipId);
                flightToDB = new Flight(flightFormViewModel.GetDateTime(), flightFormViewModel.BasePrice, flightFormViewModel.FlightPathId, starship, flightFormViewModel.IsVIP);

                flightRepository.Add(flightToDB);
            }
            else
            {
                flightToDB = flightRepository.GetSingleFlight(flightFormViewModel.FlightId);

                if (flightToDB == null)
                    return HttpNotFound();

                var starship = starshipRepository.GetSingleStarship(flightFormViewModel.StarshipId);
                flightToDB.Update(flightFormViewModel.GetDateTime(), flightFormViewModel.BasePrice, null, starship, null);
            }

            unitOfWork.Complete();

            InformViewsForCreateOrEdit(flightToDB, flightFormViewModel.FlightId);

            return RedirectToAction("Index", "Flight");
        }

        private void InformViewsForCreateOrEdit(Flight flightToDB, int viewModelsId)
        {
            //Get the flight from database with all its relations needed for a flightDto
            var flightToViews = flightRepository.GetSingleFlight(flightToDB.FlightId);

            var flightService = new FlightHubService();
            var flightStatuses = flightStatusRepository.GetFlightStatuses();

            var flightDto = Mapper.Map<Flight, FlightDto>(flightToDB);
            flightDto.FlightStatuses = flightStatuses.Select(s => Mapper.Map<FlightStatus, FlightStatusDto>(s)).ToList();
            flightDto.ConvertDate();

            if (viewModelsId == 0)
                flightService.FlightCreated(flightDto);
            else
                flightService.FlightUpdated(flightDto);

        }

        public ActionResult ManageSeats(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var flight = flightRepository.GetFullFlightWithSeats(id ?? (int)InvalidPropertyValues.undefinedValue);

            if (flight == null)
                return HttpNotFound();

            var viewModel = new FullFlightViewModel(flight);

            return View(viewModel);
        }

        [AllowAnonymous]
        public ActionResult ChooseSeats(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var flight = flightRepository.GetFullFlightWithSeats(id ?? (int)InvalidPropertyValues.undefinedValue);

            if (flight == null)
                return HttpNotFound();

            var viewModel = new FullFlightViewModel(flight);

            return View(viewModel);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [AllowAnonymous]
        public ActionResult CheckSeatAvailability(int? FlightId, long[] flightSeatIds)
        {
            if (!FlightId.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var flight = flightRepository.GetFullFlightWithSeats(FlightId ?? (int)InvalidPropertyValues.undefinedValue);

            if (flight == null)
                return HttpNotFound();

            if (flightSeatIds == null)
            {
                var viewModel = new FullFlightViewModel(flight);
                ModelState.AddModelError("MinimunSeats", "You must choose at least one seat.");
                return View("ChooseSeats", viewModel);
            }
               
            var flightSeats = flightSeatRepository.GetAvailableFlightSeatsById(flightSeatIds);

            if(flightSeats.Count != flightSeatIds.Length)
            {
                var viewModel = new FullFlightViewModel(flight);
                ModelState.AddModelError("UnavailableSeats", "One or more of the seats you choose are unavailable.");
                return View("ChooseSeats", viewModel);
            }

            Session["flight"] = flight;
            Session["flightSeats"] = flightSeats;

            //The refresh interval is used for preventing the user refresh the order page
            TempData["RefreshInterval"] = -1;

            return RedirectToAction("Create", "Order");
        }

    }
}

Space101/Controllers/api/FlightsController.cs
using Space101.DAL;
using Space101.Enums;
using Space101.Helper_Models;
using Space101.Hub_Services;
using Space101.Models;
using Space101.Persistence;
using Space101.Repositories;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Http;

namespace Space101.Controllers.api
{
    public class FlightsController : ApiController
    {
        private readonly ApplicationDbContext context;
        private readonly FlightRepository flightRepository;
        private readonly FlightSeatRepository flightSeatRepository;
        private readonly TicketRepository ticketRepository;
        private readonly OrderRepository orderRepository;
        private readonly UnitOfWork unitOfWork;

        public FlightsController()
        {
            context = new ApplicationDbContext();
            flightRepository = new FlightRepository(context);
            flightSeatRepository = new FlightSeatRepository(context);
            ticketRepository = new TicketRepository(context);
            orderRepository = new OrderRepository(context);
            unitOfWork = new UnitOfWork(context);
        }

        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }

        //Delete api/flights/id")
        [HttpDelete]
        [Authorize(Roles = AvailableRoles.Admin + "," + AvailableRoles.DatabaseManager)]
        public IHttpActionResult DeleteFlight(int? id)
        {
            if (!id.HasValue)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var flightDb = flightRepository.GetSingleFlight(id ?? (int)InvalidPropertyValues.undefinedValue);

            if (flightDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            var flightTickets = ticketRepository.GetTicketsOfFlight(flightDb.FlightId);

            if (flightTickets.Any())
                return BadRequest("The Flight has purchased Tickets!\nTo delete it contact your Database Manager.");

            flightRepository.Remove(flightDb);

            unitOfWork.Complete();

            var flightService = new FlightHubService();
            flightService.FlightDeleted(id ?? (int)InvalidPropertyValues.undefinedValue);

            return Ok();
        }

        [Route("api/flights/hardDelete/{id}")]
        [HttpDelete]
        public IHttpActionResult HardDeleteFlight(int? id)
        {
            if (!User.IsInRole(AvailableRoles.DatabaseManager))
                return BadRequest("You have not access to delete the flight.\nPlease contact your Database Manager.");

            //The HardDeleteFlight Action will remove every record in database that relates with the flight
            if (!id.HasValue)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var flightDb = flightRepository.GetSingleFlight(id ?? (int)InvalidPropertyValues.undefinedValue);

            if (flightDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            var flightTickets = ticketRepository.GetTicketsOfFlight(flightDb.FlightId);
            ClearOrders(flightTickets);
            ticketRepository.RemoveMultipleTicket(flightTickets);

            flightRepository.Remove(flightDb);

            unitOfWork.Complete();

            var flightService = new FlightHubService();
            flightService.FlightDeleted(id ?? (int)InvalidPropertyValues.undefinedValue);

            return Ok();
        }
        private void ClearOrders(IEnumerable<Ticket> tickets)
        {
            var ids = tickets.Select(t => t.TicketId);
            var orders = ticketRepository.GetTicketsOrder(ids.ToArray());
            orderRepository.RemoveMultipleOrders(orders);
        }

        [Route("api/flights/flightStatus/{id}/{statusId}")]
        [HttpPost]
        [Authorize(Roles = AvailableRoles.Admin + "," + AvailableRoles.DatabaseManager)]
        public IHttpActionResult ChangeStatus(int? id, int? statusId)
        {
            if (!id.HasValue || !statusId.HasValue)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var flightDb = flightRepository.GetSingleFlight(id ?? (int)InvalidPropertyValues.undefinedValue);

            if (flightDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            flightDb.ChangeFlightStatus(statusId ?? (int)InvalidPropertyValues.undefinedValue);

            unitOfWork.Complete();

            var flightService = new FlightHubService();
            flightService.FligthStatusChanged(id ?? (int)InvalidPropertyValues.undefinedValue, statusId ?? (int)InvalidPropertyValues.undefinedValue);

            return Ok();
        }

        [Route("api/flights/seats/releaseSeats")]
        [HttpPost]
        public IHttpActionResult ReleaseSeat([FromBody] long[] seatIds)
        {
            if (seatIds == null || seatIds.Length < 1)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var seatsToRelease = flightSeatRepository.GetFlightSeatsById(seatIds);

            if (seatsToRelease == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            var flightId = seatsToRelease[0].FlightId;
            var flightTickets = ticketRepository.GetTicketsOfFlight(flightId);

            var closedSeats = flightTickets.Where(t => seatIds.Contains(t.SeatId));

            if (closedSeats.Count() > 0)
                return BadRequest("The Seat cannot be released because a ticket is already purchased!");

            seatsToRelease.ForEach(fs => fs.ReleaseSeat());

            unitOfWork.Complete();

            var flightService = new FlightHubService();
            flightService.FlightSeatsOpened(seatIds);

            return Ok(seatIds);
        }

        [Route("api/flights/seats/holdSeats")]
        [HttpPost]
        public IHttpActionResult HoldSeats([FromBody] long[] seatIds)
        {
            if (seatIds == null || seatIds.Length < 1)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var seatsToRelease = flightSeatRepository.GetFlightSeatsById(seatIds);

            if (seatsToRelease == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            seatsToRelease.ForEach(fs => fs.HoldSeat());

            unitOfWork.Complete();

            var flightService = new FlightHubService();
            flightService.FlightSeatsClosed(seatIds);

            return Ok(seatIds);
        }
    }
}

Space101/Views/Flight/ChooseSeats.cshtml
@model Space101.ViewModels.FlightViewModels.FullFlightViewModel

@{
    ViewBag.Title = "ChooseSeats";
}

<h2>Choose Your Seats</h2>

<div class="row heading" style="margin-left: 25px;">

    <div class="col-xs-5">
        <div class="row">
            <div>
                <img src="~/images/internet.png" />  Departure Planet: @Html.DisplayFor(f => f.FlightPath.Departure.Name)
            </div>
            <div>
                <img src="~/images/internet.png" />    Destination Planet: @Html.DisplayFor(f => f.FlightPath.Destination.Name)
            </div>
            <div>
                <img src="~/images/timetable.png" />    @Html.NameFor(f => f.Date) : @Html.DisplayFor(f => f.Date)
            </div>
        </div>
    </div>

    <div class="col-xs-5">
        <div class="row">
            <div>
                <img src="~/images/ticket.png" />   Flight Status: @Html.DisplayFor(f => f.FlightStatus.StatusName)
            </div>
            <div>
                <img src="~/images/spaceship.png" />   Starship Model: @Html.DisplayFor(f => f.Starship.Model)<br />
            </div>
            <div>
                <img src="~/images/info.png" />    Starship Passenger Capacity: @Html.DisplayFor(f => f.Starship.PassengerCapacity)<br />
            </div>
        </div>
    </div>

    <div class="col-xs-2 vip">
        VIP: @(Model.IsVIP?"YES":"NO") <br />
    </div>
    

</div>

@using (Html.BeginForm("CheckSeatAvailability", "Flight"))
{
    @Html.AntiForgeryToken()

    <div class="container" id="flightSeats" data-flight-id="@Model.FlightId">
        @Html.HiddenFor(f => f.FlightId)
        @Html.ValidationMessage("MinimunSeats")
        @Html.ValidationMessage("UnavailableSeats")
        <div class="row main-row" style="">
            @{
                int counter = 1;
                string prevClass = "";
            }
            @for (var i = 0; i < Model.Seats.Count; i++)
            {
                if (prevClass != Model.Seats[i].TravelClassId)
                {
                    counter = 1;
                @:</div>
                <div class="row" style="margin-left:10px;">
                    <div class="col-md-12 travel-class">Seat Class:  @Model.Seats[i].TravelClassId - Price: @Model.Seats[i].GetPrice()$</div>
                </div>
                @: <div class="row" style="margin-left:60px; margin-right: -60px;">
                }

                <div class="col-xs-2 checkbox-div">
                    @if (Model.Seats[i].IsAvailable)
                    {
                        <div id="@Model.Seats[i].FlightSeatId">
                            <input type="checkbox" name="flightSeatIds" value="@Model.Seats[i].FlightSeatId" />
                            <span class="css-label">@Model.Seats[i].Code</span>
                        </div>
                    }
                    else
                    {
                        <div id="@Model.Seats[i].FlightSeatId" >
                            <span><input type="checkbox" class="inactive" disabled data-seat-id="@Model.Seats[i].FlightSeatId" /></span>
                            <span class="css-label-inactive">@Model.Seats[i].Code</span>
                        </div>
                    }

                </div>

                if (counter % 6 == 0)
                {
                @:</div>
                @:<div class="row" style="margin-left:60px; margin-right: -60px;">
                }

                counter++;
                prevClass = Model.Seats[i].TravelClassId;
            }
        </div>
    </div>

    <div class="row btn-row">
        <button type="submit" disabled class="btn btn-primary" id="btn-submit">Save</button>
        @Html.ActionLink("Cancel", "Flights", "UserFlights", null, new { @class = "btn btn-danger", id = "btn-cancel" })
    </div>

}

@Styles.Render("~/Content/custom/userSeat.css")

@section scripts{

    @Scripts.Render("~/bundles/flight")
    @Scripts.Render("~/bundles/signalR")

    <script>

        $(document).ready(function () {
            FlightController.initializeChooseSeatFlightHub();

            (function () {
                let checks = $("input[type=checkbox]:checked");
                let submit = $("[type=submit]");

                if (checks.length > 0) {
                    submit.attr("disabled", false);
                }
                else {
                    submit.attr("disabled", true);
                }
            })();

            $("#flightSeats").on("click", "input", function () {
                let checks = $("input[type=checkbox]:checked");
                let submit = $("[type=submit]");

                if (checks.length > 0) {
                    submit.attr("disabled", false);
                }
                else {
                    submit.attr("disabled", true);
                }
            });

            //let cleared = sessionStorage.getItem("cleared");

            //if (cleared) {
            //    sessionStorage.removeItem("cleared");
            //    window.history.back();
            //}

        });
    </script>
}

Space101/Views/Flight/FlightForm.cshtml
@model Space101.ViewModels.FlightViewModels.ContainerFlightFormViewModel
@{
    ViewBag.Title = "FlightForm";
}
<br />
@if (Model.Action == "New")
{
    <h2>Create New Flight</h2>
}
else
{
    <h2>Edit Flight With Id: @Model.FlightFormViewModel.FlightId</h2>
}
<br />
@using (Html.BeginForm("Save", "Flight"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(f => f.FlightFormViewModel.FlightId)

    <div class="row">

        <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
            <div class="form-group">
                @Html.LabelFor(f => f.FlightFormViewModel.Date, new { @class = "col-form-label" })*
                <div class='input-group date' id='datePicker'>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                    @Html.TextBoxFor(f => f.FlightFormViewModel.Date, new { @class = "form-control" })
                    @Html.ValidationMessageFor(f => f.FlightFormViewModel.Date)

                </div>
            </div>
        </div>

        <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
            <div>
                <div class="form-group">
                    @Html.LabelFor(f => f.FlightFormViewModel.Time, new { @class = "col-form-label" })*
                    <div class='input-group date' id='timePicker'>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-time"></span>
                        </span>
                        @Html.TextBoxFor(f => f.FlightFormViewModel.Time, new { @class = "form-control" })
                        @Html.ValidationMessageFor(f => f.FlightFormViewModel.Time)
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="row">

        <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
            <div class="form-group">
                @Html.LabelFor(f => f.FlightFormViewModel.BasePrice, new { @class = "col-form-label" })*
                @Html.TextBoxFor(f => f.FlightFormViewModel.BasePrice, new { @class = "form-control" })
                @Html.ValidationMessageFor(f => f.FlightFormViewModel.BasePrice)
            </div>
        </div>

        <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
            <div class="form-group">
                @Html.LabelFor(f => f.FlightFormViewModel.IsVIP)
                <div class="input-group">
                    <span class="input-group-addon">
                        @if (Model.Action == "New")
                        {
                            @Html.CheckBoxFor(f => f.FlightFormViewModel.IsVIP)
                        }
                        else
                        {
                            @Html.CheckBoxFor(f => f.FlightFormViewModel.IsVIP, new { @class = "disabled", disabled = true })
                        }
                    </span>
                    <input type="text" class="form-control" value="Check for VIP Flights" disabled />
                    @Html.ValidationMessageFor(f => f.FlightFormViewModel.IsVIP)
                </div>
            </div>
        </div>

    </div>

    <div class="row">

        <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
            <div class="form-group">
                @Html.LabelFor(f => f.FlightFormViewModel.FlightPathId, new { @class = "col-form-label" })*
                @if (Model.Action == "New")
                {
                    @Html.DropDownListFor(f => f.FlightFormViewModel.FlightPathId, new SelectList(Model.FlightPaths, "FlightPathId", "Name"), "Select FlightPath", new { @class = "form-control", id = "flightPathId" })
                }
                else
                {
                    @Html.DropDownListFor(f => f.FlightFormViewModel.FlightPathId, new SelectList(Model.FlightPaths, "FlightPathId", "Name"), "Select FlightPath", new { @class = "form-control disabled", id = "flightPathId", disabled = true })
                }
                @Html.ValidationMessageFor(f => f.FlightFormViewModel.FlightPathId)
            </div>
        </div>

        <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
            <div class="form-group">
                @Html.LabelFor(f => f.FlightFormViewModel.StarshipId, new { @class = "col-form-label" })*
                @if (Model.Action == "New")
                {
                    @Html.DropDownListFor(f => f.FlightFormViewModel.StarshipId, new SelectList(Model.Starships, "StarshipId", "Name"), "Select Starship", new { @class = "form-control", id = "StarshipId" })
                }
                else
                {
                    @Html.DropDownListFor(f => f.FlightFormViewModel.StarshipId, new SelectList(Model.Starships, "StarshipId", "Name"), "Select Starship", new { @class = "form-control disabled", id = "StarshipId", disabled = true })
                }
                @Html.ValidationMessageFor(f => f.FlightFormViewModel.StarshipId)
            </div>
        </div>

    </div>

    <div class="row">
        <button type="submit" class="btn btn-primary">Save</button>
        @Html.ActionLink("Cancel", "Index", "Flight", null, new { @class = "btn btn-danger" })
    </div>
}

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryvalCustomLocals")

    <script>

        $(document).ready(function () {
            LocalCultureController.initLocalCulture();
            CustomDateTimePick.initAfterToday(LocalCultureController.cultureName);
        });

    </script>

}

Space101/Views/Flight/ManageSeats.cshtml
@model Space101.ViewModels.FlightViewModels.FullFlightViewModel

@{
    ViewBag.Title = "ChooseSeats";
}
<br />
<h2>Manage Seats of Fligth with Id: @Model.FlightId</h2>
<br />
<div class="panel panel-info flight-information">
    <div class="panel-heading">Flight Information</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
                <dl class="dl-horizontal">
                    <dt>
                        Departure Planet:
                    </dt>
                    <dd>
                        @Html.DisplayFor(f => f.FlightPath.Departure.Name)
                    </dd>
                    <dt>
                        Destination Planet:
                    </dt>
                    <dd>
                        @Html.DisplayFor(f => f.FlightPath.Destination.Name)
                    </dd>
                    <dt>
                        Date:
                    </dt>
                    <dd>
                        @Html.DisplayFor(f => f.Date)
                    </dd>
                    <dt>
                        Base Price:
                    </dt>
                    <dd>
                        @Html.DisplayFor(f => f.BasePrice)
                    </dd>
                </dl>
            </div>
            <div class="col-md-4">
                <dl class="dl-horizontal">
                    <dt>
                        Flight Status:
                    </dt>
                    <dd>
                        @Html.DisplayFor(f => f.FlightStatus.StatusName)
                    </dd>
                    <dt>
                        Starship Model:
                    </dt>
                    <dd>
                        @Html.DisplayFor(f => f.Starship.Model)
                    </dd>
                    <dt>
                        Passenger Capacity:
                    </dt>
                    <dd>
                        @Html.DisplayFor(f => f.Starship.PassengerCapacity)
                    </dd>
                    <dt>
                        VIP:
                    </dt>
                    <dd>
                        @(Model.IsVIP?"YES":"NO")
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>

<table class="table table-responsive table-striped table-condensed" id="flight-seats">
    <thead>
        <tr>
            <th>
                Seat Id
            </th>
            <th>
                Seat Code
            </th>
            <th>
                Travel Class
            </th>
            <th>
                Current Price
            </th>
            <th>
                Availability
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var seat in Model.Seats)
        {
            <tr class="@(seat.IsAvailable?"":"danger")">
                <td>
                    @Html.DisplayFor(modelItem => seat.FlightSeatId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => seat.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => seat.TravelClassId)
                </td>
                <td>
                    @seat.GetPrice()
                </td>
                <td>
                    @(seat.IsAvailable?"OPEN":"CLOSED")
                </td>
                <td>
                    <button class="btn @(seat.IsAvailable?"btn-warning":"btn-danger") js-toggle-availability" data-seat-availability="@seat.IsAvailable" data-seat-id="@seat.FlightSeatId">@(seat.IsAvailable?"CLOSE":"OPEN")</button>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts
{
    @Scripts.Render("~/bundles/flight")
    @Scripts.Render("~/bundles/signalR")

    <script>
        $(document).ready(function () {
            FlightController.initializeAdminsSeatDataTable("#flight-seats");
            FlightController.initializeAdminsManageSeats("#flight-seats", CustomBootBoxAlerts.confirmManageSeat, CustomToasts.successManageModel, CustomToasts.failManageModel);
            FlightController.initializeAdminsManageSeatFlightHub();
        });
    </script>
}